const SUPABASE_URL = "https://qbxgufrfnwaasaotrfmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_rrpZQ5j2zetb848sT1g90Q_R0LNIsAt";

const eventImages = [
  "https://media.base44.com/images/public/6a0f6ab8b7a925941d91c273/a57a11a0a_2025-12-05.webp",
  "https://media.base44.com/images/public/6a0f6ab8b7a925941d91c273/5aee51ef8_2025-05-073.webp",
  "https://media.base44.com/images/public/6a0f6ab8b7a925941d91c273/e0248ecc3_unnamed3.webp",
];
const fallbackEvents = [
  { id: null, title: "Tropical Friday", event_date: "", start_time: "22:30", description: "House set and signature cocktails", image_url: eventImages[0] },
  { id: null, title: "Pineapple Sessions", event_date: "", start_time: "23:00", description: "DJ duo and late lounge", image_url: eventImages[1] },
  { id: null, title: "Cocktail Social", event_date: "", start_time: "20:00", description: "Bar tasting and relaxed groove", image_url: eventImages[2] },
];
const fallbackTables = [
  { id: null, table_number: "01", capacity: 4, zone: "Sank", map_left: "8%", map_top: "12%", is_vip: false },
  { id: null, table_number: "02", capacity: 4, zone: "Sank", map_left: "31%", map_top: "8%", is_vip: false },
  { id: null, table_number: "03", capacity: 6, zone: "Sprat", map_left: "58%", map_top: "12%", is_vip: true },
  { id: null, table_number: "04", capacity: 4, zone: "Sank", map_left: "80%", map_top: "18%", is_vip: false },
  { id: null, table_number: "05", capacity: 6, zone: "Lounge", map_left: "18%", map_top: "49%", is_vip: false },
  { id: null, table_number: "06", capacity: 8, zone: "VIP", map_left: "45%", map_top: "42%", is_vip: true },
  { id: null, table_number: "07", capacity: 4, zone: "Lounge", map_left: "73%", map_top: "53%", is_vip: false },
  { id: null, table_number: "08", capacity: 5, zone: "Sprat", map_left: "10%", map_top: "76%", is_vip: false },
  { id: null, table_number: "09", capacity: 6, zone: "Sprat", map_left: "61%", map_top: "78%", is_vip: false },
];
const vipPackages = [
  { name: "Gold Package", price: "25,000 RSD", detail: "Premium table, one bottle and priority seating.", features: ["4-6 guests", "Premium bottle", "Dedicated service"] },
  { name: "Platinum Package", price: "50,000 RSD", detail: "Two bottles, champagne toast and VIP entry.", features: ["6-8 guests", "Champagne toast", "Priority entry"] },
  { name: "Diamond Package", price: "100,000 RSD", detail: "Best table, full bottle service and concierge.", features: ["8-10 guests", "Sparkler show", "Concierge"] },
];
const gallery = [
  ["Pineapple cocktail show", "https://media.base44.com/images/public/6a0f6ab8b7a925941d91c273/b2779a528_2025-05-071.jpg", "wide tall"],
  ["Bar shelves", "https://media.base44.com/images/public/6a0f6ab8b7a925941d91c273/99e62382b_unnamed5.webp", ""],
  ["Bartender and guest", "https://media.base44.com/images/public/6a0f6ab8b7a925941d91c273/3f53d7114_unnamed4.webp", ""],
  ["Crystal cocktails", "https://media.base44.com/images/public/6a0f6ab8b7a925941d91c273/e0248ecc3_unnamed3.webp", "wide"],
  ["Flamingo vibes", "https://media.base44.com/images/public/6a0f6ab8b7a925941d91c273/5b6193f98_2024-11-27.webp", ""],
  ["Tropical lounge", "https://media.base44.com/images/public/6a0f6ab8b7a925941d91c273/dd4a42c11_unnamed2.webp", ""],
];
const eventGrid = document.querySelector("#event-grid"), tableMap = document.querySelector("#table-map"), vipGrid = document.querySelector("#vip-grid"), galleryGrid = document.querySelector("#gallery-grid"), modal = document.querySelector("#action-modal"), modalContent = document.querySelector("#modal-content"), selectedTitle = document.querySelector("#selected-table-title"), selectedCopy = document.querySelector("#selected-table-copy"), reserveSelected = document.querySelector("#reserve-selected"), guestForm = document.querySelector("#guest-form"), guestEvent = document.querySelector("#guest-event"), toast = document.querySelector("#toast");
let events = fallbackEvents, tables = fallbackTables, selectedTable = null;
function showToast(message, tone = "success") { toast.dataset.tone = tone; toast.textContent = message; toast.classList.add("show"); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove("show"), 3200); }
function openModal(markup) { modalContent.innerHTML = markup; modal.showModal(); }
function closeModal() { modal.close(); modalContent.innerHTML = ""; }
function escapeHtml(value) { return String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;"); }
function eventDateLabel(event) { if (!event.event_date) return event.start_time || "Uskoro"; const day = new Intl.DateTimeFormat("sr-RS", { weekday: "short", day: "numeric", month: "short" }).format(new Date(`${event.event_date}T12:00:00`)); return `${day}${event.start_time ? `, ${event.start_time.slice(0, 5)}` : ""}`; }
function eventOptions(selectedId = "") { return events.map((event) => `<option value="${escapeHtml(event.id ?? "")}" ${String(event.id ?? "") === String(selectedId) ? "selected" : ""}>${escapeHtml(event.title)} - ${escapeHtml(eventDateLabel(event))}</option>`).join(""); }
async function supabaseRequest(table, { method = "GET", query = "", body } = {}) { const response = await fetch(`${SUPABASE_URL}/rest/v1/${table}${query}`, { method, headers: { apikey: SUPABASE_PUBLISHABLE_KEY, "Content-Type": "application/json", Accept: "application/json", ...(method === "POST" ? { Prefer: "return=minimal" } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) }); if (!response.ok) throw new Error((await response.text()) || `Supabase ${method} request failed.`); return response.status === 204 ? null : response.json(); }
function renderEvents() { eventGrid.innerHTML = events.map((event, index) => `<article class="event-card"><img src="${escapeHtml(event.image_url || eventImages[index % eventImages.length])}" alt="${escapeHtml(event.title)}" /><div class="event-body"><div class="event-top"><div><p class="eyebrow">${escapeHtml(eventDateLabel(event))}</p><h3>${escapeHtml(event.title)}</h3></div><span class="pill">RSVP</span></div><p class="event-meta">${escapeHtml(event.description || "Rezervisi mesto za sledece vece.")}</p><button class="button secondary" type="button" data-rsvp="${escapeHtml(event.id ?? "")}">Prijavi dolazak</button></div></article>`).join(""); guestEvent.innerHTML = eventOptions(); }
function renderTables() { tableMap.innerHTML = tables.map((table) => `<button class="table ${table.is_vip ? "vip" : ""}" type="button" style="left:${escapeHtml(table.map_left || "10%")};top:${escapeHtml(table.map_top || "10%")}" data-table="${escapeHtml(table.table_number)}" aria-label="Sto ${escapeHtml(table.table_number)}, ${escapeHtml(table.capacity)} mesta, ${escapeHtml(table.zone)}${table.is_vip ? ", VIP" : ""}"><strong>${escapeHtml(table.table_number)}</strong><span>${table.is_vip ? "VIP" : `${escapeHtml(table.capacity)} mesta`}</span></button>`).join(""); }
function renderStaticSections() { vipGrid.innerHTML = vipPackages.map((pkg) => `<article class="package-card" tabindex="0" role="button" data-package="${escapeHtml(pkg.name)}"><div class="package-top"><div><p class="eyebrow">Bottle service</p><h3>${escapeHtml(pkg.name)}</h3></div><span class="price">${escapeHtml(pkg.price)}</span></div><p>${escapeHtml(pkg.detail)}</p><div class="feature-list">${pkg.features.map((feature) => `<span>${escapeHtml(feature)}</span>`).join("")}</div></article>`).join(""); galleryGrid.innerHTML = gallery.map(([label, url, size]) => `<button class="gallery-button ${escapeHtml(size)}" type="button" data-gallery-label="${escapeHtml(label)}" data-gallery-url="${escapeHtml(url)}"><img src="${escapeHtml(url)}" alt="${escapeHtml(label)}" /></button>`).join(""); }
function bookingForm({ mode, title, intro, submitLabel, selectedEventId = "" }) { return `<div class="modal-stack"><p class="eyebrow">Booking</p><h3>${escapeHtml(title)}</h3><p class="muted">${escapeHtml(intro)}</p><form class="modal-form two" data-booking-form data-mode="${escapeHtml(mode)}"><label>Ime<input name="name" autocomplete="name" required placeholder="Ime i prezime" /></label><label>Telefon<input name="phone" autocomplete="tel" required placeholder="+381..." /></label>${mode === "guest" ? "" : `<label class="${mode === "reservation" ? "wide" : ""}">Email<input name="email" autocomplete="email" type="email" placeholder="email@example.com" /></label>`}<label>Dogadjaj<select name="event" required>${eventOptions(selectedEventId)}</select></label><label>Broj gostiju<input name="guests" type="number" min="1" max="12" value="4" required /></label><label class="wide">Napomena<textarea name="note" placeholder="Rodjendan, omiljeni sto, posebna boca..."></textarea></label><button class="button primary wide" type="submit">${escapeHtml(submitLabel)}</button></form></div>`; }
async function loadSupabaseData() { try { const [databaseEvents, databaseTables] = await Promise.all([supabaseRequest("events", { query: "?select=id,title,event_date,start_time,description,image_url,status&status=eq.upcoming&order=event_date.asc" }), supabaseRequest("venue_tables", { query: "?select=id,table_number,zone,capacity,is_vip,map_left,map_top&is_active=eq.true&order=table_number.asc" })]); if (databaseEvents.length) events = databaseEvents; if (databaseTables.length) tables = databaseTables; renderEvents(); renderTables(); } catch (error) { console.error(error); renderEvents(); renderTables(); showToast("Baza trenutno nije dostupna. Prikazujem demo podatke.", "warning"); } }
async function submitGuestList(formData, eventId) { await supabaseRequest("guest_list_entries", { method: "POST", body: { guest_name: formData.get("name").trim(), guest_phone: formData.get("phone").trim(), event_id: Number(eventId), party_size: Number(formData.get("guests")), status: "pending" } }); }
async function submitReservation(formData, selectedEvent) { await supabaseRequest("reservations", { method: "POST", body: { guest_name: formData.get("name").trim(), guest_phone: formData.get("phone").trim(), guest_email: formData.get("email").trim() || null, event_id: Number(selectedEvent.id), table_id: selectedTable.id, party_size: Number(formData.get("guests")), reservation_date: selectedEvent.event_date || null, note: formData.get("note").trim() || null, status: "pending" } }); }
async function submitVipInquiry(formData, selectedEvent, packageName) { await supabaseRequest("vip_inquiries", { method: "POST", body: { package_name: packageName, guest_name: formData.get("name").trim(), guest_phone: formData.get("phone").trim(), guest_email: formData.get("email").trim() || null, event_id: Number(selectedEvent.id), party_size: Number(formData.get("guests")), note: formData.get("note").trim() || null, status: "pending" } }); }
eventGrid.addEventListener("click", (event) => { const button = event.target.closest("[data-rsvp]"); if (!button) return; const selectedEvent = events.find((item) => String(item.id ?? "") === button.dataset.rsvp); openModal(bookingForm({ mode: "guest", title: selectedEvent?.title || "Guest list", intro: "Prijava se cuva u bazi i ceka potvrdu.", submitLabel: "Posalji RSVP", selectedEventId: selectedEvent?.id ?? "" })); });
tableMap.addEventListener("click", (event) => { const button = event.target.closest("[data-table]"); if (!button) return; selectedTable = tables.find((table) => table.table_number === button.dataset.table); document.querySelectorAll(".table").forEach((table) => table.classList.remove("selected")); button.classList.add("selected"); selectedTitle.textContent = `Sto ${selectedTable.table_number}`; selectedCopy.textContent = `${selectedTable.zone} zona, ${selectedTable.capacity} mesta${selectedTable.is_vip ? ", VIP service dostupan" : ""}.`; reserveSelected.disabled = false; });
reserveSelected.addEventListener("click", () => { if (selectedTable) openModal(bookingForm({ mode: "reservation", title: `Sto ${selectedTable.table_number}`, intro: `${selectedTable.zone} zona za ${selectedTable.capacity} gostiju.`, submitLabel: "Posalji rezervaciju" })); });
vipGrid.addEventListener("click", (event) => { const card = event.target.closest("[data-package]"); if (!card) return; const pkg = vipPackages.find((item) => item.name === card.dataset.package); openModal(bookingForm({ mode: "vip", title: pkg.name, intro: `${pkg.detail} Cena paketa: ${pkg.price}`, submitLabel: "Posalji VIP upit" })); modal.querySelector("[data-booking-form]").dataset.package = pkg.name; });
galleryGrid.addEventListener("click", (event) => { const button = event.target.closest("[data-gallery-url]"); if (button) openModal(`<div class="modal-stack"><img class="lightbox-image" src="${escapeHtml(button.dataset.galleryUrl)}" alt="${escapeHtml(button.dataset.galleryLabel)}" /><p class="muted">${escapeHtml(button.dataset.galleryLabel)}</p></div>`); });
modal.addEventListener("submit", async (event) => { const form = event.target.closest("[data-booking-form]"); if (!form) return; event.preventDefault(); const submitButton = form.querySelector('button[type="submit"]'), formData = new FormData(form), selectedEvent = events.find((item) => String(item.id ?? "") === String(formData.get("event"))); if (!selectedEvent?.id) return showToast("Dogadjaj jos nije spreman u bazi. Pokusaj ponovo.", "error"); submitButton.disabled = true; submitButton.textContent = "Saljem..."; try { if (form.dataset.mode === "guest") { await submitGuestList(formData, selectedEvent.id); showToast("RSVP prijava je sacuvana."); } else if (form.dataset.mode === "reservation") { await submitReservation(formData, selectedEvent); showToast("Rezervacija je poslata i ceka potvrdu."); } else { await submitVipInquiry(formData, selectedEvent, form.dataset.package); showToast("VIP upit je poslat i ceka potvrdu."); } closeModal(); } catch (error) { console.error(error); submitButton.disabled = false; submitButton.textContent = "Pokusaj ponovo"; showToast("Slanje nije uspelo. Provericemo bazu i pravila pristupa.", "error"); } });
guestForm.addEventListener("submit", async (event) => { event.preventDefault(); const formData = new FormData(guestForm), submitButton = guestForm.querySelector('button[type="submit"]'); submitButton.disabled = true; submitButton.textContent = "Saljem..."; try { await submitGuestList(formData, formData.get("event")); guestForm.reset(); guestEvent.selectedIndex = 0; showToast("Guest list prijava je sacuvana."); } catch (error) { console.error(error); showToast("Guest list prijava nije poslata.", "error"); } finally { submitButton.disabled = false; submitButton.textContent = "Posalji prijavu"; } });
document.querySelector(".modal-close").addEventListener("click", closeModal); modal.addEventListener("click", (event) => { if (event.target === modal) closeModal(); }); const menuToggle = document.querySelector(".menu-toggle"), headerNav = document.querySelector(".site-header nav"); menuToggle.addEventListener("click", () => { const open = headerNav.classList.toggle("open"); menuToggle.setAttribute("aria-expanded", String(open)); }); headerNav.addEventListener("click", () => { headerNav.classList.remove("open"); menuToggle.setAttribute("aria-expanded", "false"); });
renderStaticSections(); renderEvents(); renderTables(); loadSupabaseData();
